export function map(){
    var svg = d3.select("#nba-map");
    var path = d3.geoPath();
    const mapinfor = "../../data/states-albers-10m.json"
    let western = ["Washington","Oregon","California","Nevada","Idaho","Arizona","Utah","New Mexico","Colorado","Montana","Wyoming","Colorado","Texas","Oklahoma","Kansas","Nebraska","South Dakota","North Dakota","Minnesota","Iowa","Missouri","Arkansas","Tennessee","Louisiana","Hawaii","Alaska"]
    svg = d3.select('#nba-map')
    let stateData
    function drawMap(){
        svg.append('g')
            .attr('class', 'state')
            .selectAll('path')
            .data(stateData)
            .enter()
            .append('path')
            .attr('d', d3.geoPath())
            .attr('class', 'state')
            .attr("fill", (el)=>{
                let stateName = el.properties.name
                if (western.includes(stateName)){
                    return "lightblue"
                } else {
                    return "pink"
                }
            })
            legend()
            mapTeam()
    }

    d3.json(mapinfor).then(
        (data,error)=>{
            if(error){
                console.log(error)
            } else {
                stateData = topojson.feature(data, data.objects.states).features
                drawMap()
            }
        }
        )
};

export function legend(){
    var svg = d3.select("#nba-map");
    svg.append("circle").attr("cx", 550).attr("cy", 550).attr("r", 10).style("fill", "lightblue")
    svg.append("circle").attr("cx", 550).attr("cy", 580).attr("r", 10).style("fill", "pink")
    svg.append("text").attr("x", 570).attr("y", 553).text("Western Conference").style("font-size", "15px").attr("alignment-baseline", "middle")
    svg.append("text").attr("x", 570).attr("y", 583).text("Eastern Conference").style("font-size", "15px").attr("alignment-baseline", "middle")
}

export function mapTeam(){
    
    let svg = d3.select('#nba-map')
    const team = svg.append("g")
        .attr("class", "team")

    team.append('image')
        .attr('id', 'LAL')
        .attr('x', 75)
        .attr('y', 345)
        .attr("link:href", "../../image/LAL.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Los Angeles Laker')
        .attr('data-location','Crypto.com Arena, Los Angeles, CA')
        .attr('data-intro', "The Los Angeles Lakers are an American professional basketball team based in Los Angeles. The Lakers compete in the National Basketball Association as a member of the league's Western Conference Pacific Division.")
        .attr('data-topplayers', 'LeBron James, Russell Westbrook, Anthony Davis')
        .attr('data-numchamp','17 (1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, 2010, 2020)')


    team.append('image')
        .attr('id', 'LAC')
        .attr('x', 60)
        .attr('y', 315)
        .attr("link:href", "../../image/LAC.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Los Angeles Clippers')
        .attr('data-location', 'Crypto.com Arena, Los Angeles, CA')
        .attr('data-intro', "The Los Angeles Clippers are an American professional basketball team based in Los Angeles. The Clippers compete in the National Basketball Association as a member of the Pacific Division in the league's Western Conference")
        .attr('data-topplayers', 'Kawhi Leonard, John Wall, Paul George')
        .attr('data-numchamp', 'None')


    team.append('image')
        .attr('id', 'SAC')
        .attr('x', 45)
        .attr('y', 215)
        .attr("link:href", "../../image/SAC.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Sacramento Kings')
        .attr('data-location', 'Golden 1 Center, Sacramento, CA')
        .attr('data-intro', "The Sacramento Kings are an American professional basketball team based in Sacramento, California. The Kings compete in the National Basketball Association (NBA) as a member of the Western Conference Pacific Division. The Kings are the first and only team in the major professional North American sports leagues located in Sacramento. The team plays its home games at the Golden 1 Center. Their best seasons to date in the city were in the early 2000s, including a very successful 2001–02 season when they had the best record in the NBA at 61–21 (a winning percentage of .744).")
        .attr('data-topplayers', "Domantas Sabonis, De'Aaron Fox, Davion Mitchell")
        .attr('data-numchamp', '1 (1951)')

    team.append('image')
        .attr('id', 'GSW')
        .attr('x', 20)
        .attr('y', 245)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-golden-state-warriors-logo-2020-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Golden State Warriors')
        .attr('data-location', 'Chase Center, San Francisco, CA')
        .attr('data-intro', "The Golden State Warriors are an American professional basketball team based in San Francisco. The Warriors compete in the National Basketball Association (NBA), as a member of the league's Western Conference Pacific Division. Founded in 1946 in Philadelphia, the Warriors moved to the San Francisco Bay Area in 1962 and took the city's name, before changing its geographic moniker to Golden State in 1971.[a][b] The club plays its home games at the Chase Center.")
        .attr('data-topplayers', "Stephen Curry, Draymond Green, Klay Thompson")
        .attr('data-numchamp', '7 (1947, 1956, 1975, 2015, 2017, 2018, 2022)')


    team.append('image')
        .attr('id', 'PHX')
        .attr('x', 180)
        .attr('y', 350)
        .attr("link:href", "../../image/PHX.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Phoenix Suns')
        .attr('data-location', 'Footprint Center, Phoenix, AR')
        .attr('data-intro', "The Phoenix Suns are an American professional basketball team based in Phoenix, Arizona. They compete in the National Basketball Association (NBA), as a member of the league's Western Conference Pacific Division. The Suns are the only team in their division not to be based in California, and play their home games at the Footprint Center. The Suns are one of four major league sports teams based in the Phoenix area, but are the only one to bill themselves as representing the city (the other teams - the Cardinals, Coyotes, and Diamondbacks - all bill themselves as representing the state of Arizona).")
        .attr('data-topplayers', "Devin Booker, Chris Paul, Deandre Ayton")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'POR')
        .attr('x', 45)
        .attr('y', 60)
        .attr("link:href", "../../image/POR.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Portland Trail Blazers')
        .attr('data-location', 'Moda Center,Portland, OR')
        .attr('data-intro', "The Portland Trail Blazers (colloquially known as the Blazers) are an American professional basketball team based in Portland, Oregon. The Trail Blazers compete in the National Basketball Association (NBA) as a member of the league's Western Conference Northwest Division. The team played its home games in the Memorial Coliseum before moving to the Moda Center in 1995 (called the Rose Garden until 2013). The franchise entered the league as an expansion team in 1970, and has enjoyed a strong following: from 1977 through 1995, the team sold out 814 consecutive home games, the longest such streak in American major professional sports at the time, and only since surpassed by the Boston Red Sox. The Trail Blazers are the only NBA team based in the Pacific Northwest, after the Vancouver Grizzlies relocated to Memphis and became the Memphis Grizzlies in 2001 and the Seattle SuperSonics relocated to Oklahoma City and became the Oklahoma City Thunder in 2008.")
        .attr('data-topplayers', "Damian Lillard, Anfernee Simons, Jerami Grant")
        .attr('data-numchamp', '1 (1977)')

    team.append('image')
        .attr('id', 'UTA')
        .attr('x', 205)
        .attr('y', 215)
        .attr("link:href", "../../image/UTA.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Utah Jazz')
        .attr('data-location', 'Vivint Arena, Salt Lake City, UT')
        .attr('data-intro', "The Utah Jazz are an American professional basketball team based in Salt Lake City. The Jazz compete in the National Basketball Association (NBA) as a member of the league's Western Conference, Northwest Division. Since the 1991–92 season, the team has played its home games at Vivint Arena. The franchise began play as an expansion team in the 1974–75 season as the New Orleans Jazz (as a tribute to New Orleans' history of originating jazz music). The Jazz relocated to Salt Lake City prior to the 1979–80 season.")
        .attr('data-topplayers', "Donovan Mitchell, Jordan Clarkson, Bojan Bogdanović")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'DEN')
        .attr('x', 315)
        .attr('y', 240)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-denver-nuggets-logo-2018-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Denver Nuggets')
        .attr('data-location', 'Ball Arena, Denver, CO')
        .attr('data-intro', "The Denver Nuggets are an American professional basketball team based in Denver. The Nuggets compete in the National Basketball Association (NBA) as a member of the league's Western Conference Northwest Division. The team was founded as the Denver Larks in 1967 as a charter franchise of the American Basketball Association (ABA), but changed their name to Rockets before the first season. The Rockets then changed their name again to the Nuggets in 1974. After the name change, the Nuggets played for the final ABA Championship title in 1976, losing to the New York Nets.")
        .attr('data-topplayers', "Nikola Jokić, Jamal Murray, DeMarcus Cousins")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'MIN')
        .attr('x', 485)
        .attr('y', 95)
        .attr("link:href", "../../image/MIN.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Minnesota Timberwolves')
        .attr('data-location', 'Target Center, Minneapolis, MN')
        .attr('data-intro', "The Minnesota Timberwolves are an American professional basketball team based in Minneapolis. The Timberwolves compete in the National Basketball Association (NBA) as a member of the league's Western Conference Northwest Division.Founded in 1989, the team is owned by Glen Taylor who also owns the WNBA's Minnesota Lynx. The Timberwolves play their home games at Target Center, their home since 1990.Like most expansion teams, the Timberwolves struggled in their early years, but after the acquisition of Kevin Garnett in the 1995 NBA draft, the team qualified for the playoffs in eight consecutive seasons from 1997 to 2004. Despite losing in the first round in their first seven attempts, the Timberwolves won their first division championship in 2004 and advanced to the Western Conference Finals that same season.Garnett was also named the NBA Most Valuable Player for that season. The team then went into rebuilding mode for more than a decade after missing the postseason in 2005, and trading Garnett to the Boston Celtics in 2007. Garnett returned to the Timberwolves in a February 2015 trade and finished his career there, retiring in the 2016 offseason.The Timberwolves ended a 14 - year playoff drought when they returned to the postseason in 2018.")
        .attr('data-topplayers', "Anthony Edwards, Rudy Gobert, Karl-Anthony Towns")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'OKC')
        .attr('x', 440)
        .attr('y', 335)
        .attr("link:href", "../../image/KOC.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Oklahoma City Thunder')
        .attr('data-location', 'Paycom Center, Oklahoma City, OK')
        .attr('data-intro', "The Oklahoma City Thunder are an American professional basketball team based in Oklahoma City. The Thunder compete in the National Basketball Association (NBA) as a member of the league's Western Conference Northwest Division. The team plays its home games at Paycom Center. The team was originally established as the Seattle SuperSonics, an expansion team that joined the NBA for the 1967–68 season. The SuperSonics relocated from Seattle, Washington to Oklahoma City in 2008 after a settlement was reached between the ownership group led by Clay Bennett and lawmakers in Seattle following a lawsuit. In Seattle, the SuperSonics qualified for the NBA playoffs 22 times, won their division six times, advanced to three NBA Finals, and won the 1979 NBA Championship. In Oklahoma City, the Thunder qualified for their first playoff berth during the 2009–10 season. They won their first division title as the Thunder in the 2010–11 season and their first Western Conference championship as the Thunder in the 2011–12 season, appearing in the NBA Finals for the fourth time in franchise history and first time since 1996, when the team was based in Seattle. The team has yet to win a championship since moving to Oklahoma City.")
        .attr('data-topplayers', "Chet Holmgren, Josh Giddey, Shai Gilgeous-Alexander")
        .attr('data-numchamp', '1 (1979)')

    team.append('image')
        .attr('id', 'DAL')
        .attr('x', 450)
        .attr('y', 410)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-dallas-mavericks-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Dallas Mavericks')
        .attr('data-location', 'American Airlines Center, Dallas, TX')
        .attr('data-intro', "The Dallas Mavericks (often referred to as the Mavs) are an American professional basketball team based in Dallas. The Mavericks compete in the National Basketball Association (NBA) as a member of the Western Conference Southwest Division. The team plays its home games at the American Airlines Center, which it shares with the National Hockey League's Dallas Stars. Throughout the 1980s, the Mavericks were a perennial playoff team, led by All - Stars Rolando Blackman and Mark Aguirre.The team struggled during the 1990s, entering into a period of rebuilding.In 1998, the franchise's fortunes would change drastically with the acquisition of Dirk Nowitzki, who would become the cornerstone of the most successful period in franchise history, leading the team to its first NBA championship in 2011. The Mavericks later entered a rebuilding phase in the tail end of Nowitzki's storied career.They missed the playoffs in three consecutive years from 2017 to 2019, after which Nowitzki retired following his record - breaking 21st season with Dallas.Led by 2019 Rookie of the Year Luka Dončić, the Mavericks returned to the playoffs in 2020 and reached the Western Conference Finals in 2022 for the first time since their 2011 championship. In February 2020, the Mavericks sold out their NBA - record 815th consecutive game, dating back to December 15, 2001. The sellout streak, which includes 67 playoff games, is the longest currently running in North American major league sports. Currently, the Dallas Mavericks are owned by investor Mark Cuban.Since the Mavericks' inaugural 1980–81 season, the Mavericks have won four division titles (1987, 2007, 2010, 2021), two conference championships (2006, 2011), and one NBA championship (2011).")
        .attr('data-topplayers', "Luka Dončić, Christian Wood, Spencer Dinwiddie")
        .attr('data-numchamp', '1 (2011)')

    team.append('image')
        .attr('id', 'SAS')
        .attr('x', 425)
        .attr('y', 530)
        .attr("link:href", "../../image/SAS.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'San Antonio Spurs')
        .attr('data-location', 'AT&T Center, San Antonio, TX')
        .attr('data-intro', "The San Antonio Spurs are an American professional basketball team based in San Antonio. The Spurs compete in the National Basketball Association (NBA) as a member of the league's Western Conference Southwest Division. The team plays its home games at the AT&T Center in San Antonio. ")
        .attr('data-topplayers', "Jakob Poeltl, Keldon Johnson, Joshua Primo")
        .attr('data-numchamp', ' 5 (1999, 2003, 2005, 2007, 2014)')

    team.append('image')
        .attr('id', 'HOU')
        .attr('x', 490)
        .attr('y', 490)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-houston-rockets-logo-2020-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Houston Rockets')
        .attr('data-location', 'Toyota Center, Houston, TX')
        .attr('data-intro', "The Houston Rockets are an American professional basketball team based in Houston. The Rockets compete in the National Basketball Association (NBA) as a member team of the league's Western Conference Southwest Division. The team plays its home games at the Toyota Center, located in Downtown Houston. Throughout its history, Houston has won two NBA championships and four Western Conference titles. It was established in 1967 as the San Diego Rockets, an expansion team originally based in San Diego. In 1971, the Rockets relocated to Houston. ")
        .attr('data-topplayers', "Jalen Green, Kevin Porter Jr., Jabari Smith Jr.")
        .attr('data-numchamp', ' 2 (1994, 1995)')

    team.append('image')
        .attr('id', 'NOL')
        .attr('x', 590)
        .attr('y', 485)
        .attr("link:href", "../../image/NOL.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'New Orleans Pelicans')
        .attr('data-location', 'Smoothie King Center, New Orleans, LA')
        .attr('data-intro', "The New Orleans Pelicans (often referred to as the Pels) are an American professional basketball team based in New Orleans. The Pelicans compete in the National Basketball Association (NBA) as a member of the league's Western Conference Southwest Division and play their home games at the Smoothie King Center. The NBA considers New Orleans an expansion team that began play in the 2002–03 season. The Pelicans were established as the New Orleans Hornets in the 2002–03 season when George Shinn, then owner of the Charlotte Hornets, relocated the franchise to New Orleans. Due to the damage caused by Hurricane Katrina in 2005, the team temporarily relocated to Oklahoma City, where they spent two seasons as the New Orleans/Oklahoma City Hornets before returning to New Orleans for the 2007–08 season. In 2013, the Hornets announced that they would change their name to the New Orleans Pelicans after the 2012–13 season. In 18 seasons of play since the original franchise relocated from Charlotte, the New Orleans franchise has achieved an overall regular season record of 740–864 (.461) and qualified for the playoffs eight times. Their achievements include two playoff series victories and one division title.")
        .attr('data-topplayers', "Brandon Ingram, Zion Williamson, CJ McCollum")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'MEM')
        .attr('x', 590)
        .attr('y', 350)
        .attr("link:href", "../../image/MEM.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Memphis Grizzlies')
        .attr('data-location', 'FedExForum, Memphis, TN')
        .attr('data-intro', "The Memphis Grizzlies (referred to locally as the Grizz) are an American professional basketball team based in Memphis, Tennessee. The Grizzlies compete in the National Basketball Association (NBA) as a member of the league's Western Conference Southwest Division. The Grizzlies play their home games at FedExForum. The team is owned by Robert Pera. The Grizzlies are currently the only team in the major professional North American sports leagues based in the city of Memphis, and the only professional basketball team in the state of Tennessee. The team was originally established as the Vancouver Grizzlies in the city of Vancouver, Canada, an expansion team that joined the NBA for the 1995–96 season.After the 2000–01 season concluded, the Grizzlies left Vancouver and moved to Memphis. ")
        .attr('data-topplayers', "Ja Morant, Steven Adams., Jaren Jackson Jr.")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'CHI')
        .attr('x', 600)
        .attr('y', 205)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-chicago-bulls-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Chicago Bulls')
        .attr('data-location', 'United Center, Chicago, IL')
        .attr('data-intro', "The Chicago Bulls are an American professional basketball team based in Chicago. The Bulls compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Central Division. The team was founded on January 16, 1966, and played its first game during the 1966–67 NBA season. The Bulls play their home games at the United Center, an arena on Chicago's West Side.")
        .attr('data-topplayers', "Zach LaVine, Lonzo Ball, DeMar DeRozan")
        .attr('data-numchamp', '6 (1991, 1992, 1993, 1996, 1997, 1998)')


    team.append('image')
        .attr('id', 'MIL')
        .attr('x', 600)
        .attr('y', 165)
        .attr("link:href", "../../image/MIL.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Milwaukee Bucks')
        .attr('data-location', 'Fiserv Forum, Milwaukee, WI')
        .attr('data-intro', "The Milwaukee Bucks are an American professional basketball team based in Milwaukee. The Bucks compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Central Division. The team was founded in 1968 as an expansion team, and play at Fiserv Forum. Former U.S. Senator Herb Kohl was the long-time owner of the team, but on April 16, 2014, a group led by billionaire hedge fund managers Wes Edens and Marc Lasry agreed to purchase a majority interest in the team from Kohl, a sale which was approved by the owners of the NBA and its Board of Governors one month later on May 16. The team is managed by Jon Horst the team's former director of basketball operations, who took over from John Hammond.")
        .attr('data-topplayers', "Giannis Antetokounmpo, Khris Middleton,Jrue Holiday")
        .attr('data-numchamp', '2 (1971, 2021)')

    team.append('image')
        .attr('id', 'IND')
        .attr('x', 640)
        .attr('y', 250)
        .attr("xlink:href", "../../image/IND.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Indiana Pacers')
        .attr('data-location', 'Bankers Life Fieldhouse, Indianapolis, IN')
        .attr('data-intro', "The Indiana Pacers are an American professional basketball team based in Indianapolis. The Pacers compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Central Division. The Pacers were first established in 1967 as a member of the American Basketball Association (ABA) and became a member of the NBA in 1976 as a result of the ABA–NBA merger. They play their home games at Gainbridge Fieldhouse. The team is named after the state of Indiana's history with the Indianapolis 500's pace cars and with the harness racing industry. The Pacers have won three championships, all in the ABA.The Pacers were NBA Eastern Conference champions in 2000. The team has won nine division titles.Six Hall of Fame players – Reggie Miller, Chris Mullin, Alex English, Mel Daniels, Roger Brown, and George McGinnis – played with the Pacers for multiple seasons.")
        .attr('data-topplayers', "Tyrese Haliburton, Myles Turner, Jalen Smith")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'CLE')
        .attr('x', 695)
        .attr('y', 200)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/cleveland-cavaliers-2010-2017-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Cleveland Cavaliers')
        .attr('data-location', 'ocket Mortgage FieldHouse, Cleveland, OH')
        .attr('data-intro', "The Cleveland Cavaliers (often referred to as the Cavs) are an American professional basketball team based in Cleveland. The Cavaliers compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Central Division. The team began play as an expansion team in 1970, along with the Portland Trail Blazers and Buffalo Braves. Home games were first held at Cleveland Arena from 1970 to 1974, followed by the Richfield Coliseum from 1974 to 1994. Since 1994, the Cavs have played home games at Rocket Mortgage FieldHouse in downtown Cleveland, which is shared with the Cleveland Monsters of the American Hockey League. Dan Gilbert has owned the team since March 2005.")
        .attr('data-topplayers', "Collin Sexton, Kevin Love, Darius Garland")
        .attr('data-numchamp', '1 (2016)')

    team.append('image')
        .attr('id', 'DET')
        .attr('x', 660)
        .attr('y', 180)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-detroit-pistons-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Detroit Pistons')
        .attr('data-location', 'Little Caesars Arena, Detroit, MI')
        .attr('data-intro', "The Detroit Pistons are an American professional basketball team based in Detroit. The Pistons compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Central Division and play their home games at Little Caesars Arena, located in Midtown. Founded in Fort Wayne, Indiana as a semi-professional company basketball team called the Fort Wayne Zollner Pistons in 1937, they would turn pro in 1941 as a member of the National Basketball League (NBL), where they won two NBL championships: in 1944 and 1945. The Pistons later joined the Basketball Association of America (BAA) in 1948. The NBL and BAA merged to become the NBA in 1949, and the Pistons became part of the merged league.In 1957, the franchise moved to Detroit. ")
        .attr('data-topplayers', "Jaden Ivey, Cade Cunningham, Jalen Duren")
        .attr('data-numchamp', '3 (1989, 1990, 2004)')

    team.append('image')
        .attr('id', 'TOR')
        .attr('x', 740)
        .attr('y', 140)
        .attr("link:href", "../../image/TOR.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Toronto Raptors')
        .attr('data-location', 'Scotiabank Arena, Toronto, Canada')
        .attr('data-intro', "The Toronto Raptors are a Canadian professional basketball team based in Toronto. The Raptors compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Atlantic Division. They play their home games at Scotiabank Arena, which they share with the Toronto Maple Leafs of the National Hockey League (NHL). The team was founded in 1995 as part of the NBA's expansion into Canada, along with the Vancouver Grizzlies. Since the 2001–02 season, the Raptors have been the only Canadian-based team in the league, as the Grizzlies relocated from Vancouver to Memphis, Tennessee.")
        .attr('data-topplayers', "Scottie Barnes, Pascal Siakam, OG Anunoby")
        .attr('data-numchamp', '1 (2019)')

    team.append('image')
        .attr('id', 'BOS')
        .attr('x', 885)
        .attr('y', 150)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-boston-celtics-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Boston Celtics')
        .attr('data-location', 'TD Garden, Boston, MA')
        .attr('data-intro', "The Boston Celtics are an American professional basketball team based in Boston. The Celtics compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Atlantic Division. Founded in 1946 as one of the league's original eight teams, the Celtics play their home games at TD Garden, which they share with the National Hockey League's Boston Bruins. The Celtics are one of the most successful basketball teams in NBA history. The franchise is one of two teams with 17 NBA Championships, the other franchise being the Los Angeles Lakers. The Celtics currently hold the record for the most recorded wins of any NBA team.")
        .attr('data-topplayers', "Jayson Tatum, Jaylen Brown, Marcus Smart")
        .attr('data-numchamp', '17 (1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969, 1974, 1976, 1981, 1984, 1986, 2008)')


    team.append('image')
        .attr('id', 'BKN')
        .attr('x', 870)
        .attr('y', 180)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-brooklyn-nets-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Brooklyn Nets')
        .attr('data-location', 'Barclays Center, Brooklyn, NY')
        .attr('data-intro', "The Brooklyn Nets are an American professional basketball team based in the New York City borough of Brooklyn. The Nets compete in the National Basketball Association (NBA) as a member of the Atlantic Division of the Eastern Conference. The team plays its home games at Barclays Center. They are one of two NBA teams located in New York City; the other is the New York Knicks. The club was established in 1967 as a charter franchise of the NBA's rival league, the American Basketball Association (ABA). They played in New Jersey as the New Jersey Americans during their first season, before relocating to Long Island, New York, in 1968 and changing their name to the New York Nets.")
        .attr('data-topplayers', "Kevin Durant, Kyrie Irving, Ben Simmons")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'NYK')
        .attr('x', 840)
        .attr('y', 180)
        .attr("link:href", "../../image/NYK.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'New York Knicks')
        .attr('data-location', 'Madison Square Garden, New York, NY')
        .attr('data-intro', "The New York Knickerbockers, shortened and more commonly referred to as the New York Knicks, are an American professional basketball team based in the New York City borough of Manhattan. The Knicks compete in the National Basketball Association (NBA) as a member of the Atlantic Division of the Eastern Conference. The team plays its home games at Madison Square Garden, an arena they share with the New York Rangers of the National Hockey League (NHL). They are one of two NBA teams located in New York City; the other team is the Brooklyn Nets. Alongside the Boston Celtics, the Knicks are one of two original NBA teams still located in its original city.")
        .attr('data-topplayers', "Jalen Brunson, Derrick Rose, RJ Barrett")
        .attr('data-numchamp', '2 (1970, 1973)')

    team.append('image')
        .attr('id', 'PHI')
        .attr('x', 830)
        .attr('y', 210)
        .attr("link:href", "../../image/PHI.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Philadelphia 76ers')
        .attr('data-location', 'Wells Fargo Center, Philadelphia, PA')
        .attr('data-intro', "The Philadelphia 76ers, colloquially known as the Sixers, are an American professional basketball team based in the Philadelphia metropolitan area. The 76ers compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Atlantic Division and play at the Wells Fargo Center. Founded in 1946 and originally known as the Syracuse Nationals, they are one of the oldest franchises in the NBA and one of only eight (out of 23) to survive the league's first decade.")
        .attr('data-topplayers', "James Harden, Joel Embiid, Tyrese Maxey")
        .attr('data-numchamp', '3 (1955, 1967, 1983)')

    team.append('image')
        .attr('id', 'WAS')
        .attr('x', 800)
        .attr('y', 240)
        .attr("link:href", "../../image/WAS.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Washington Wizards')
        .attr('data-location', 'Capital One Arena, Washington, D.C.')
        .attr('data-intro', "The Washington Wizards are an American professional basketball team based in Washington, D.C. The Wizards compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Southeast Division. The team plays its home games at the Capital One Arena, in the Chinatown neighborhood of Washington, D.C.")
        .attr('data-topplayers', "Bradley Beal, Kyle Kuzma, Kristaps Porziņģis")
        .attr('data-numchamp', '1 (1978)')

    team.append('image')
        .attr('id', 'ATL')
        .attr('x', 690)
        .attr('y', 380)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-atlanta-hawks-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Atlanta Hawks')
        .attr('data-location', 'State Farm Arena, Atlanta, GA')
        .attr('data-intro', "The Atlanta Hawks are an American professional basketball team based in Atlanta. The Hawks compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Southeast Division. The team plays its home games at State Farm Arena.")
        .attr('data-topplayers', "Trae Young, Dejounte Murray, John Collins")
        .attr('data-numchamp', '1 (1958)')

    team.append('image')
        .attr('id', 'CHA')
        .attr('x', 745)
        .attr('y', 340)
        .attr("link:href", "https://loodibee.com/wp-content/uploads/nba-charlotte-hornets-logo-300x300.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Charlotte Hornets')
        .attr('data-location', 'Spectrum Center, Charlotte, NC')
        .attr('data-intro', "The Boston Celtics are an American professional basketball team based in Boston. The Celtics compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Atlantic Division. Founded in 1946 as one of the league's original eight teams, the Celtics play their home games at TD Garden, which they share with the National Hockey League's Boston Bruins. The Celtics are one of the most successful basketball teams in NBA history. The franchise is one of two teams with 17 NBA Championships, the other franchise being the Los Angeles Lakers. The Celtics currently hold the record for the most recorded wins of any NBA team.")
        .attr('data-topplayers', "LaMelo Ball, Miles Bridges, Gordon Hayward")
        .attr('data-numchamp', '0')

    team.append('image')
        .attr('id', 'ORL')
        .attr('x', 780)
        .attr('y', 500)
        .attr("link:href", "../../image/ORL.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Orlando Magic')
        .attr('data-location', 'Amway Center, Orlando, FL')
        .attr('data-intro', "The Orlando Magic are an American professional basketball team based in Orlando, Florida. The Magic compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Southeast Division. The franchise was established in 1989 as an expansion franchise, and such notable NBA stars as Shaquille O'Neal, Penny Hardaway, Grant Hill, Tracy McGrady, Dwight Howard, Jameer Nelson, Rashard Lewis and Nikola Vučević have played for the club throughout its history. As of 2021, the franchise has played in the NBA playoffs 16 times in 32 seasons, and twice went to the NBA Finals, in 1995 and 2009. Orlando has been the second most successful of the four expansion teams brought into the league in 1988 and 1989 in terms of winning percentage and playoff success, after the Miami Heat")
        .attr('data-topplayers', "Paolo Banchero, Bol Bol, Mohamed Bamba")
        .attr('data-numchamp', '1 (2019)')

    team.append('image')
        .attr('id', 'MIA')
        .attr('x', 800)
        .attr('y', 560)
        .attr("link:href", "../../image/MIA.png")
        .attr('width', 50)
        .attr('height', 50)
        .attr('data-name', 'Miami Heat')
        .attr('data-location', 'TX Arena, Miami, FL')
        .attr('data-intro', "The Miami Heat are an American professional basketball team based in Miami. The Heat compete in the National Basketball Association (NBA) as a member of the league's Eastern Conference Southeast Division. The club plays its home games at FTX Arena, and has won three NBA championships.")
        .attr('data-topplayers', "Jimmy Butler, Tyler Herro, Bam Adebayo")
        .attr('data-numchamp', '3 (2006, 2012, 2013)')
}

