export function map(){
    var svg = d3.select("svg");
    var path = d3.geoPath();
    const width = parseFloat(svg.attr('width'))
    const height = parseFloat(svg.attr('height'))
    d3.json("https://d3js.org/us-10m.v1.json", function (error, us) {
        if (error) throw error;


        svg.append("g")
            .attr("class", "states") 
            .selectAll("path")
            .data(topojson.feature(us, us.objects.states).features)
            .enter().append("path")
            .attr("d", path);

        svg.append("path")
            .attr("class", "state-borders")
            .attr("d", path(topojson.mesh(us, us.objects.states, function (a, b) { return a !== b; })));

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'LAL')
            .attr('x', 70)
            .attr('y', 330)
            .attr("link:href", "../../image/LAL.png")
            .attr('width', 50)
            .attr('height', 50)


        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'LAC')
            .attr('x',55)
            .attr('y', 300)
            .attr("link:href", "../../image/LAC.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'SAC')
            .attr('x', 40)
            .attr('y', 210)
            .attr("link:href", "../../image/SAC.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'GSW')
            .attr('x', 15)
            .attr('y', 240)
            .attr("link:href", "../../image/GSW.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'PHX')
            .attr('x', 180)
            .attr('y', 350)
            .attr("link:href", "../../image/PHX.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'POR')
            .attr('x', 45)
            .attr('y', 60)
            .attr("link:href", "../../image/POR.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'UTA')
            .attr('x', 195)
            .attr('y', 205)
            .attr("link:href", "../../image/UTA.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'DEN')
            .attr('x', 315)
            .attr('y', 240)
            .attr("link:href", "../../image/DEN.png")
            .attr('width', 50)
            .attr('height', 50)
        
        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'MIN')
            .attr('x', 485)
            .attr('y', 95)
            .attr("link:href", "../../image/MIN.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'KOC')
            .attr('x', 440)
            .attr('y', 335)
            .attr("link:href", "../../image/KOC.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'DAL')
            .attr('x', 450)
            .attr('y', 410)
            .attr("link:href", "../../image/DAL.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'SAS')
            .attr('x', 415)
            .attr('y', 480)
            .attr("link:href", "../../image/SAS.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'HOU')
            .attr('x', 475)
            .attr('y', 470)
            .attr("link:href", "../../image/HOU.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'NOL')
            .attr('x', 580)
            .attr('y', 475)
            .attr("link:href", "../../image/NOL.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'MEM')
            .attr('x', 590)
            .attr('y', 350)
            .attr("link:href", "../../image/MEM.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'CHI')
            .attr('x', 590)
            .attr('y', 210)
            .attr("link:href", "../../image/CHI.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'MIL')
            .attr('x', 580)
            .attr('y', 165)
            .attr("link:href", "../../image/MIL.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'CLE')
            .attr('x', 695)
            .attr('y', 200)
            .attr("link:href", "../../image/CLE.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'DET')
            .attr('x', 660)
            .attr('y', 180)
            .attr("link:href", "../../image/DET.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'TOR')
            .attr('x', 730)
            .attr('y', 140)
            .attr("link:href", "../../image/TOR.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'BOS')
            .attr('x', 870)
            .attr('y', 140)
            .attr("link:href", "../../image/BOS.png")
            .attr('width', 50)
            .attr('height', 50)


        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'NYK')
            .attr('x', 830)
            .attr('y', 170)
            .attr("link:href", "../../image/NYK.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'BKN')
            .attr('x', 860)
            .attr('y', 180)
            .attr("link:href", "../../image/BKN.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'PHI')
            .attr('x', 820)
            .attr('y', 200)
            .attr("link:href", "../../image/PHI.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'WAS')
            .attr('x', 790)
            .attr('y', 230)
            .attr("link:href", "../../image/WAS.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'ATL')
            .attr('x', 680)
            .attr('y', 370)
            .attr("link:href", "../../image/ATL.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'CHA')
            .attr('x', 735)
            .attr('y', 330)
            .attr("link:href", "../../image/CHA.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'ORL')
            .attr('x', 760)
            .attr('y', 480)
            .attr("link:href", "../../image/ORL.png")
            .attr('width', 50)
            .attr('height', 50)

        svg.append('image')
            .attr('class', 'team-logo')
            .attr('id', 'MIA')
            .attr('x', 780)
            .attr('y', 540)
            .attr("link:href", "../../image/MIA.png")
            .attr('width', 50)
            .attr('height', 50)
    });
}